//Using exports rather than module.exports bc this is not a fn
exports.newWord = {
  wordList:
    [ 'BERKELIUM', 'HYDROGEN', 'TITANIUM', 'MANGANESE', 'GERMANIUM', 'VANADIUM', 'ARSENIC', 'STRONTIUM', 'YTTRIUM', 'ZIRCONIUM', 'RUTHENIUM', 'PRASEODYMIUM', 'ZIRCONIUM', 'PRASEODYMIUM', 'YTTRIUM', 'PLATINUM', 'TUNGSTEN', 'PLUTONIUM', 'CALIFORNIUM', 'URANIUM', 'BISMUTH', 'NEPTUNIUM', 'LAWRENCIUM', 'EINSTEINIUM' ]
};